# Generated by Django 3.2 on 2023-06-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='customer', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(default='hospital', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentPatient',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.hospital'),
        ),
    ]
