# Generated by Django 3.2 on 2023-07-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_alter_patient_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madokta', to='Hospital.hospital')),
            ],
        ),
    ]
