# Generated by Django 3.2 on 2023-07-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
