# Generated by Django 3.2 on 2023-07-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_remove_hospital_no_of_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
