# Generated by Django 3.2 on 2023-08-27 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_auto_20230827_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Hospital.department'),
        ),
    ]
