# Generated by Django 3.2 on 2023-09-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=500)),
                ('hospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.hospital')),
            ],
        ),
    ]
