# Generated by Django 3.2 on 2023-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0015_hospitalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=500),
        ),
    ]
