# Generated by Django 3.2 on 2023-09-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0016_hospitalbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbooking',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='Hospital.hospital'),
        ),
    ]
