# Generated by Django 3.2 on 2023-09-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0018_alter_hospitalbooking_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbooking',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Hospital.hospital'),
        ),
    ]
