# Generated by Django 3.2 on 2023-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0019_alter_hospitalbooking_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
