# Generated by Django 3.2 on 2023-09-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0021_hospitalbooking_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbooking',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bukings', to='Hospital.department'),
        ),
    ]
