# Generated by Django 3.2 on 2023-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0022_alter_hospitalbooking_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
