# Generated by Django 3.2 on 2023-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0023_hospitalbooking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
